apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-filer-public
  namespace: seaweedfs
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: filer
  ports:
    - name: http
      port: 8888
      targetPort: 8888
