apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-s3-public
  namespace: seaweedfs
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: s3
  ports:
    - name: http
      port: 8333
      targetPort: 8333
